services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: splitshare
      POSTGRES_PASSWORD: splitshare
      POSTGRES_DB: splitshare
    ports:
      - '5432:5432'
    volumes:
      - splitshare_pg:/var/lib/postgresql/data

volumes:
  splitshare_pg:
